cmake_minimum_required(VERSION 3.16)
project(yolo_rest CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(NCNN_INSTALL_DIR /ncnn/build-clang/install)
find_package(ncnn REQUIRED)
find_package(Threads REQUIRED)
add_executable(yolo_server server.cpp)
target_include_directories(yolo_server PRIVATE third_party ${NCNN_INSTALL_DIR}/include)
target_link_libraries(yolo_server ncnn Threads::Threads)
